### ISSUE TITLE
TextArea doesn't shrink when text is removed

### ISSUE THREAD

**Issue by ThisWillDoIt** [stevepapa/ng-autosize#2]
When adding new lines/more text the directive works perfectly, but when text is removed it should shrink accordingly.

**Comment by stevepapa** [comment]
Can you please provide steps to reproduce this? It should adjust as normal whenever content of the textarea changes.

**Comment by ThisWillDoIt** [comment]
I was able to identify that in my case there seems to be a conflict with material design for bootstrap (bootstrap-material-design)

I am using version 0.5.10 , which is the newest version that is still working with bootstrap 3.
As soon as I stop referencing the bootstrap-material-design.css ng-autosize shrinks as it should.

Not sure if there is anything you can do about it. I want to drop bootstrap-material-design soon anyhow.

**Comment by stevepapa** [comment]
It sounds like you have CSS somewhere in your project that is modifying the textarea styling. I would inspect with a browser and disable textarea CSS items one by one until you find the culprit.

**Comment by whyboris** [comment]
This may be the culprit: https://github.com/stevepapa/ng-autosize/issues/6
Specifically, when the textarea has `border: 0`
