### ISSUE TITLE
[maxHeight] should not have `px`

### ISSUE THREAD

**Issue by whyboris** [stevepapa/ng-autosize#5]
It looks like `[maxHeight]="100px"` is incorrect and should instead be `[maxHeight]="100"`

https://github.com/stevepapa/ng-autosize/blame/master/README.md#L50
Similarly for `[minHeight]`
https://github.com/stevepapa/ng-autosize/blame/master/README.md#L44

**Comment by stevepapa** [comment]
Thanks Boris, this is a typo in the documentation. Update coming.
